### ISSUE TITLE
Extend the Provider Shoot spec for adding DNS and TLS definition

### ISSUE THREAD

**Issue by linuxbsdfreak** [kyma-incubator/terraform-provider-gardener#75]
**Description**

I have the below snippet in the current shoot.yaml in the gardener dashboard which includes DNS and SSL management via gardener. 

```
addons:
    kubernetesDashboard:
      enabled: true
      authenticationMode: basic
    nginxIngress:
      enabled: false
      externalTrafficPolicy: Cluster
  cloudProfileName: aws
  dns:
    domain: fmi6fdoux2.PROJ_NAME.shoot.canary.k8s-hana.ondemand.com
    providers:
      - domains:
          include:
            - example.ondemand.com
            - example2.ondemand.com
        secretName: projectname-staging-gardener
        type: aws-route53
  extensions:
    - type: shoot-dns-service
    - type: shoot-cert-service
      providerConfig:
        apiVersion: service.cert.extensions.gardener.cloud/v1alpha1
        issuers:
          - email: email_id@sap.com
            name: ondemand.com
            server: 'https://acme-v02.api.letsencrypt.org/directory'
```

**Reasons**

Makes managing the DNS and SSL easier via gardener shoot.yaml. 

How would i extend the spec to include such feature in the provider or which files do i need to edit for making it common accross all cloud providers ?

**Attachments**
